### ISSUE TITLE
Macros bug

### ISSUE THREAD

**Issue by 1MoreRaiday** [Satanaelcode/DarkClient#1]
### Describe the feature

![image](https://user-images.githubusercontent.com/123898931/222234727-11d454a0-d026-459c-b728-ce6c94a0e8ba.png)
i think it adds space at the start of macrose-sended message
This didnt happed just 10 mins before on original meteor client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Satanaelcode** [comment]
This problem is because of the Version diffrence its a meteor problem we didnt play around with it
